#注册中心配置
spring:
  port: 8080
  application:
    name: omega-eureka

#常规配置
#eureka需要超时读取之前需要等待的时间
eureka:
  client:
    eureka-server-read-timeout-seconds: 11
    #eureka客户端允许所有eureka服务器连接的总数目,默认是200
    EurekaServerTotalConnections: 200
    #允许连接最大注册数量
    EurekaServerTotalConnectionsPerHost: 50
    #Eureka服务的http请求关闭之前其响应的时间，默认为30 秒
    EurekaConnectionIdleTimeoutSeconds: 30
    service-url:
      defaultZone: http://localhost:8080/eureka/
    #实例是在eureka服务器上注册自己的信息以供其他服务发现
    register-with-eureka: false
    #此客户端是否获取eureka服务器注册表上的注册信息,默认为true
    fetch-registry: false

#关闭自带security验证
management:
  security:
    enabled: false

logging:
  config: classpath:logback.xml
